"""add_asset_price_history

Revision ID: 5667813b8c40
Revises: de9f750cb929
Create Date: 2026-03-18 21:50:50.776997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5667813b8c40'
down_revision: Union[str, Sequence[str], None] = 'de9f750cb929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_price_history_asset_recorded', 'asset_price_history', ['asset_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('ix_asset_price_history_id'), 'asset_price_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_price_history_id'), table_name='asset_price_history')
    op.drop_index('ix_asset_price_history_asset_recorded', table_name='asset_price_history')
    op.drop_table('asset_price_history')
    # ### end Alembic commands ###
