"""Add asset_prices

Revision ID: 9704b3110231
Revises: f3948fcdff53
Create Date: 2026-04-02 14:55:58.569973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9704b3110231'
down_revision: Union[str, Sequence[str], None] = 'f3948fcdff53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_prices_asset_id'), 'asset_prices', ['asset_id'], unique=False)
    op.create_index('ix_asset_prices_asset_id_recorded_at', 'asset_prices', ['asset_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_asset_prices_recorded_at'), 'asset_prices', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_prices_recorded_at'), table_name='asset_prices')
    op.drop_index('ix_asset_prices_asset_id_recorded_at', table_name='asset_prices')
    op.drop_index(op.f('ix_asset_prices_asset_id'), table_name='asset_prices')
    op.drop_table('asset_prices')
    # ### end Alembic commands ###
